/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Gradle.GCMS;

public class Library {
    public boolean someLibraryMethod() {
    	System.out.println("Hello World");
        return true;
    }
}
